### PR TITLE
Created Android family grouping and other OS updates

### PR DESCRIPTION
**Pull request by brentil**
Added Android family to operating_systems.pm for enhanced reporting on Android C to O versions
Added Android family icons
Added Mac OS 10.13 High Sierra to operating_systems.pm
Updated operating_systems.pm Windows family broken links as most of them pointed to URLs that didn't exist anymore
Updated Apple MAC OS X links to be HTTPS

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Nice work! I'll consider my own PR for macOS 10.13 (#67), which has yet to be merged, superseded by yours.

**Comment by brentil** [comment]
I rebased to the 7.7 code and found no conflicts with this pull request.

**Comment by AaronVanGeffen** [comment]
It looks like you've merged the new commits in rather than rebasing your work on top of them.

It's quite a shame to see this hasn't made it into 7.7, though... 😕

**Comment by brentil** [comment]
> It looks like you've merged the new commits in rather than rebasing your work on top of them.
> It's quite a shame to see this hasn't made it into 7.7, though... 😕

I'm still really new to using GIT, I thought I had done it right.  Can you explain what I should have done to do it correctly?  I had read the github docks on rebasing but I must have not understood them then.

**Pull request merged**
