### PR TITLE
Correct typos and grammar found by codespell/etc.

### PR DESCRIPTION
**Pull request by shlomif**
Correct typos and grammar found by codespell/etc. Some stuff was not corrected yet.

### CODE REVIEW

**Comment by shlomif** [comment]
Thanks for merging it, @eldy

**Comment by eldy** [comment]
You're welcome.

It seems that you make a lot of contrib about grammar and code spelling on
open source project.
My main important and most ambitious project (dolibarr erp crm at
https://github.com/Dolibarr/dolibarr , already no 1 in France and spain,
but not very popular in english spoken country) is missing contribution
like this, most contributor are latin country (france, italy, spain, south
america) and so, english information are often not correctly wrote.

Can I make you a small donation in exchange of such contribs for this
project ?

**Comment by shlomif** [comment]
Hi Laurent,

On Wed, 17 Aug 2016 12:10:38 -0700
Laurent Destailleur notifications@github.com wrote:

> You're welcome.
> 
> It seems that you make a lot of contrib about grammar and code spelling on
> open source project.

Yes, quite a bit.

> My main important and most ambitious project (dolibarr erp crm at
> https://github.com/Dolibarr/dolibarr , already no 1 in France and spain,
> but not very popular in english spoken country) is missing contribution
> like this, most contributor are latin country (france, italy, spain, south
> america) and so, english information are often not correctly wrote.

I've already detected some spelling and grammar problems in its description and
README from a quick cursory look.

> Can I make you a small donation in exchange of such contribs for this
> project ?

Yes, you can, but here are several words of warning. The first is that I'm not
a native English speaker (I'm Israeli and my mother language is Hebrew) and as
a result may miss correcting some incorrect idioms. The second is that there
was at least one case where I was hired to do some proof reading (in Hebrew
though) and although I reported and corrected some problems, the people who
hired me told me they were still unhappy and we ended up agreeing that I
won't get paid. I'd rather this situation not repeat itself here.

If you agree to tolerate these caveats that I may miss reporting and correcting
some problems, then I can get started on the English proof-reading/correction
process.

Regards,

```
Shlomi Fish
```

**Comment by eldy** [comment]
Thanks for your frankness.
We were looking for native English speaker, but, well, your english should be better than the one of french people that is just not english at all   ;-) 
So may be. I will speak of this with other guy of the Dolibarr project and go back to you if we decide something.

**Comment by shlomif** [comment]
@eldy: OK, thank you for returning to me. I shall await the final verdict.

**Pull request merged**
