### PR TITLE
Update operating systems with data from PR74

### PR DESCRIPTION
**Pull request by mikelolasagasti**
- Add Android category
- Add Android 9 and 10 detection
- Add MacOS X 10.15 detection
- Change URL for some Windows versions
- Change URL for some Linux distributions

Signed-off-by: Mikel Olasagasti Uranga <mikel@olasagasti.info>

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Could this, or a PR like it, please be merged? The official list of operating systems has been outdated for quite a while.

**Comment by brentil** [comment]
I came to make these changes myself but I see @mikelolasagasti got them added in before me.  Just curious but whats holding up all of the various PRs from being actioned on?  I wanted to make some better sections for Windows Servers information too but if it's just going to sit in PR limbo I'm not sure what the point is.

**Comment by mfilocha** [comment]
New icons in this PR are simple symbolic links. That may not work with some web servers with strict symlinks policy.

**Comment by brentil** [comment]
> New icons in this PR are simple symbolic links. That may not work with some web servers with strict symlinks policy.

I can confirm they don't work on Windows IIS server, I had to copy over existing actual images to make it work.

**Comment by AaronVanGeffen** [comment]
I've taken the liberty to rebase this PR on top of current develop: #157

**Comment by AaronVanGeffen** [comment]
The changes from this PR have been merged as part of #157. This can be closed.

**Comment by Bllacky** [comment]
This should be closed as these changes have already been applied by other pull requests.

**Comment by eldy** [comment]
Seems already integrated with other PR. So discarded.

**Pull request closed without merging**
