### PR TITLE
Add report about request time

### PR DESCRIPTION
**Pull request by edytuk**
Add report about request time. It has 7 time intervals and counts how many hits are in each interval. It allows to see how much time is usually spent processing the client request and how frequent is each interval. This report have been used at CERN for many years. Most of the code was not written by me but by my predecessor.

#171 and #172 pull requests can not both be applied cleanly to the same code base since they conflict with each other. One of them will need to have conflicts removed after the other is merged. I will take care of it once one of pull requests is merged.

### CODE REVIEW

**Comment by eldy** [comment]
Can you help me to solve the conflict. Another PR add another text message so adding yours means rest of code don't use the correct index id in message.

**Comment by edytuk** [comment]
Merge conflicts were solved. Once this PR is merged, I will fix conflicts for #171

**Comment by eldy** [comment]
Merging the PR #171 has introduced other conflict with this Pr #172 
Can you fix them ?

**Comment by edytuk** [comment]
Merge conflicts were solved.

**Comment by DrDaveD** [comment]
Can this be merged?  Is there something preventing it?

**Comment by DrDaveD** [comment]
@eldy, what do you think?

**Comment by DrDaveD** [comment]
@eldy Can this please be completed?  @edytuk is leaving her position and we would like this to be wrapped up.

**Comment by DrDaveD** [comment]
Thank you!

**Pull request merged**
